services:
  db:
    image: postgres:16-alpine
    restart: on-failure
    ports:
      - "5432:5432"
    volumes:
      - wegym_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: A12345fe
      POSTGRES_DB: wegym
volumes:
  wegym_data:
